<html xmlns:fb="http://ogp.me/ns/fb#">

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- 
<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/"
 data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div> -->

<?php
/**
 * Implements hook_node_view().
 *
 * Returns the renderable view of our nodes (pages or articles).
 * We want to moddify the code so that we add the like button
 * to our pages.
 */
function facebook_node_view($node, $view_mode, $langcode)
{
  $node->content['facebook'] = array(
    '#markup' => theme('facebook_add_like_button'),
  );
}

/**
 * Implements hook_theme().
 *
 * Just to let Drupal know about our theme function.
 */
function facebook_theme()
{
  return array(
    'facebook_add_like_button' => array('variables' => NULL),
  );
}

/**
 * Function to add the desired code to our page.
 */
function theme_facebook_add_like_button()
{
  $output = '<fb:like href="http://myDrupalSite.com" send="true" width="450" show_faces="true"></fb:like>';
 
  return $output;
}


?>


